# Generated by Django 5.0 on 2024-01-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256, verbose_name='url')),
                ('course', models.CharField(max_length=20, verbose_name='課程名稱')),
                ('lecturer', models.CharField(max_length=20, verbose_name='授課者')),
            ],
        ),
    ]
