# Generated by Django 5.0 on 2024-03-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_area', '0002_phasedescription_alter_filminfo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phasedescription',
            name='description',
            field=models.CharField(max_length=60, verbose_name='段落重點'),
        ),
        migrations.AlterField(
            model_name='phasedescription',
            name='end',
            field=models.CharField(max_length=12, verbose_name='結尾時間'),
        ),
        migrations.AlterField(
            model_name='phasedescription',
            name='start',
            field=models.CharField(max_length=12, verbose_name='起始時間'),
        ),
    ]
